# Generated by Django 3.2.6 on 2021-09-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20210901_1924"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="info_box",
            field=models.JSONField(null=True),
        ),
    ]
