# Generated by Django 3.2.6 on 2021-09-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_topic_info_box"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="author",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="source",
            name="notes",
            field=models.TextField(null=True),
        ),
    ]
